### PR TITLE
fix(Legend): Add room for scrollbar to display

### LINKED ISSUE #3488: Chart Panel (Pie Chart) Scrollbar Covering Text
Thank you for fixing all these little bugs so quickly.  You guys rock!

I've got one more, which I tried to fix myself a bit with some CSS, but alas I could not seem to get it to do what I needed.  

When using a pie chart and setting the '.legend_labelMaxWidth' on the ChartPanel, the scrollbars do appear, which is awesome, but there seems to be a bit of missing padding on the right for the vertical scrollbar and the text sometimes gets covered by it:

image

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #3488

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [x] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:
I've viewed the related gallery and dermatology items.

### CODE REVIEW

File: packages/common/src/SVGWidget.ts [hunk 1]
```diff
@@ -301,8 +301,10 @@ export class SVGWidget extends Widget {
                 if ((transX < 0 || transY < 0) && this._boundingBox) {
                     transX = transX < 0 ? 0 : transX;
                     transY = transY < 0 ? 0 : transY;
-                    this._parentRelativeDiv.style("overflow", "scroll");
-                    this._placeholderElement.attr("width", this._boundingBox.width);
+                    this._parentRelativeDiv.style("overflow-y", "scroll");
+                    this._parentRelativeDiv.style("overflow-x", "hidden");
+                    this._parentRelativeDiv.style("width", this._boundingBox.width + 8 + getScrollbarWidth() + "px");
+                    this._placeholderElement.attr("width", this._boundingBox.width + 8 + getScrollbarWidth());
```
Comment (GordonSmith) [inline packages/common/src/SVGWidget.ts]: image

I suspect that fix should be here:  https://github.com/hpcc-systems/Visualization/blob/master/packages/layout/src/Border2.ts#L132 ?

**Comment by GordonSmith** [comment]
@jbrundage - bump

File: packages/common/src/SVGWidget.ts (hunk 1 above)
Comment (jbrundage) [reply packages/common/src/SVGWidget.ts]: I've not been able to recreate that issue outside of playground. I'm working on it though.
