### PR TITLE
fix(Bar): Alternative approach to Axis Icon mappings

### LINKED ISSUE #3606: Map Bar Icon to a field from origRow
Hi,

I would like to request for a feature to have a field from the origRow be the indicator of what icon I am going to display in the xAxisLabelMapping or maybe a different function name for this.

`const origRow = ['foobar', 20, { type: 'car' }];`
`const bar = new Bar().xAxisFontFamily('"Font Awesome 5 Pro"')`
`.xAxisLabelMapping({}, [{ field: 'type', value: 'car', icon: '' }]);`

### PR DESCRIPTION
**Pull request by GordonSmith**
Tweaked default global compile to work in GIT Bash

Fixes #3606

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

File: packages/chart/src/Column.ts [hunk 1]
```diff
@@ -280,11 +280,8 @@ export class Column extends XYAxis {
                     if (context.showInnerText()) {
                         _texts
                             .text((d: any) => {
-                                let innerText = d.row[0];
+                                const innerText = context.innerText(d.origRow, d.origRow[columnLength], d.idx);
                                 if (innerText) {
-                                    if (innerText instanceof Array) {
-                                        innerText = innerText[d.idx - 1];
-                                    }
```
Comment (GordonSmith) [inline packages/chart/src/Column.ts:287]: @jbrundage - why was this code needed?

Comment (jbrundage) [reply packages/chart/src/Column.ts:287]: It allowed for custom labels for each series in a category (when dealing with ND data)

Comment (GordonSmith) [reply packages/chart/src/Column.ts:287]: @jbrundage Can you show me an example (as I removed this code?)
