### PR TITLE
fix(timeline): Calc EntityPin height

### LINKED ISSUE #2674: MiniGantt cuts off top of event pins when the event pin text contains a linebreak

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #2674

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

File: packages/common/src/EntityPin.ts [hunk 1]
```diff
@@ -72,6 +49,41 @@ export class EntityPin extends Entity {
         this.moveAnnotations(background_bbox.width / 2, anno_y);
 
     }
+    calcHeight() {
+        const is_hovering = true;
+        this._icon_widget.render();
+        this._desc_widget.render();
+        this._title_widget.render();
```
Comment (GordonSmith) [inline packages/common/src/EntityPin.ts]: You can get the height of the above widgets without rendering them...

**Comment by jbrundage** [comment]
@GordonSmith this is ready to be reviewed
