### PR TITLE
fix: Column/Bar events moved to parent dataCell

### LINKED ISSUE #3631: Bar Chart: Make Inner Text and Value be part of the on click event of the chartPanel
Hi,

We would like to request for the onclick event of the chartPanel to include everything within the bar (innerText and value).

Thank you!

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #3631

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

File: packages/chart/src/Column.ts [hunk 1]
```diff
@@ -306,7 +307,7 @@ export class Column extends XYAxis {
                     const dataTextEnter = dataText.enter().append("g")
                         .attr("class", "dataText")
                         .each(function (this: SVGElement, d) {
-                            context.textLocal.set(this, new Text().target(this));
+                            context.textLocal.set(this, new Text().target(this).colorStroke_default("transparent"));
```
Comment (GordonSmith) [inline packages/chart/src/Column.ts:310]: Why is "transparent" needed by default?

Comment (jbrundage) [reply packages/chart/src/Column.ts:310]: When the parent element has the "over" class (added on hover) this style is applied to the inner text:
https://github.com/hpcc-systems/Visualization/blob/master/packages/api/src/ITooltip.css#L77
