### PR TITLE
fix(scatter): Add interpolatePoint property

### LINKED ISSUE #3078: Line Chart w/Chart Panel Colors
When using a line chart in a chart panel, there seems to be a slight discrepancy between the colors in the legend and the colors of the lines.  When styling the lines a little thicker, this becomes more obvious.

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #3078

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [x] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:
Tested the publish property on the dermatology page

### CODE REVIEW

File: packages/chart/src/Scatter.ts [hunk 1]
```diff
@@ -339,14 +339,20 @@ export interface Scatter {
...
 Scatter.prototype.publish("pointSizeScale", "linear", "set", "pointSizeScale", ["linear", "pow", "log", "sqrt"]);
 Scatter.prototype.publish("pointShape", "cross", "set", "Shape of the data points", ["circle", "rectangle", "cross"]);
 Scatter.prototype.publish("pointSize", 6, "number", "Point Size", null, { range: { min: 1, step: 1, max: 200 } });
 Scatter.prototype.publish("interpolate", "", "set", "Interpolate Data", ["", "linear", "step", "step-before", "step-after", "basis", "bundle", "cardinal", "catmullRom", "natural", "monotone"]);
-Scatter.prototype.publish("interpolateFill", false, "boolean", "Fill Interpolation");
-Scatter.prototype.publish("interpolateFillOpacity", 0.66, "number", "Fill Interpolation Opacity", null, { range: { min: 0, step: 0.01, max: 1 } });
+Scatter.prototype.publish("pointDarken", true, "boolean", "If true, and interpolate is set, then points will have a slightly darker color than their assigned palette color");
+Scatter.prototype.publish("interpolateDarken", true, "boolean", "If true, and interpolateFill is true, then lines will have a slightly darker color than their assigned palette color");
```
Comment (GordonSmith) [inline packages/chart/src/Scatter.ts]: add "disable" function

File: packages/chart/src/Scatter.ts [hunk 2]
```diff
@@ -339,14 +339,20 @@ export interface Scatter {
...
+    interpolateDarken(_: boolean): this;
 }
 Scatter.prototype.publish("paletteID", "default", "set", "Color palette for this widget", Scatter.prototype._palette.switch(), { tags: ["Basic", "Shared"] });
 Scatter.prototype.publish("pointSizeScale", "linear", "set", "pointSizeScale", ["linear", "pow", "log", "sqrt"]);
 Scatter.prototype.publish("pointShape", "cross", "set", "Shape of the data points", ["circle", "rectangle", "cross"]);
 Scatter.prototype.publish("pointSize", 6, "number", "Point Size", null, { range: { min: 1, step: 1, max: 200 } });
 Scatter.prototype.publish("interpolate", "", "set", "Interpolate Data", ["", "linear", "step", "step-before", "step-after", "basis", "bundle", "cardinal", "catmullRom", "natural", "monotone"]);
-Scatter.prototype.publish("interpolateFill", false, "boolean", "Fill Interpolation");
-Scatter.prototype.publish("interpolateFillOpacity", 0.66, "number", "Fill Interpolation Opacity", null, { range: { min: 0, step: 0.01, max: 1 } });
+Scatter.prototype.publish("pointDarken", true, "boolean", "If true, and interpolate is set, then points will have a slightly darker color than their assigned palette color");
```
Comment (GordonSmith) [inline packages/chart/src/Scatter.ts]: Add "disable" function
