### PR TITLE
fix: Apply font-family to inner text element

### LINKED ISSUE #3626: Bar Chart Inner Text Ellipsis overlaps value
Hi,

It seems that bar chart inner text ellipsis overlaps value. See example:

image

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #3626

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

File: packages/chart/src/Column.ts [hunk 1]
```diff
@@ -256,6 +256,10 @@ export class Column extends XYAxis {
                         .style("fill", (d: any) => context.textColor(d.row, d.column, d.value, d.origRow))
                         ;
 
+                    if(context.innerTextFontFamily_exists()){
+                        _texts.style("font-family", context.innerTextFontFamily());
+                    }
+
```
Comment (GordonSmith) [inline packages/chart/src/Column.ts:262]: Should be:

```
_texts.style("font-family", context.innerTextFontFamily_exists()?context.innerTextFontFamily():null);
```
